name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    uses: whodrey-labs/homelab-actions/.github/workflows/deploy-homelab.yml@main
    with:
      deploy_path: /home/whodrey/docker/sites/${{ github.event.repository.name }}
      compose_file: compose.yml
      branch: main
      use_tailscale: true
    secrets: inherit
